### ISSUE TITLE
null pointer dereference in src/openrct2-ui/windows/Ride.cpp

### ISSUE THREAD

**Issue by gibmat** [OpenRCT2/OpenRCT2#26117]
### Operating System

Linux

### OpenRCT2 build

0.4.32

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

Compiling OpenRCT2 0.4.32 errors out with a null pointer deference error:

```
In member function 'void OpenRCT2::Ui::Windows::RideWindow::ColourOnDrawEntrancePreview(OpenRCT2::Drawing::RenderTarget&, const Ride*, const OpenRCT2::Widget&)',
    inlined from 'void OpenRCT2::Ui::Windows::RideWindow::ColourOnDrawSecondaryPreview(OpenRCT2::Drawing::RenderTarget&, const Ride*)' at /build/openrct2-0.4.32+ds/src/openrct2-ui/windows/Ride.cpp:4970:40,
    inlined from 'void OpenRCT2::Ui::Windows::RideWindow::ColourOnDraw(OpenRCT2::Drawing::RenderTarget&)' at /build/openrct2-0.4.32+ds/src/openrct2-ui/windows/Ride.cpp:4842:41:
/build/openrct2-0.4.32+ds/src/openrct2-ui/windows/Ride.cpp:4976:54: error: null pointer dereference [-Werror=null-dereference]
 4976 |             if (stationObj == nullptr && stationObj->entranceBackIndex == kImageIndexUndefined)
      |                                          ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

I suspect `stationObj == nullptr` was meant to be `stationObj != nullptr`.

### Steps to reproduce

Compile the current release.

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/25c7379b4660c06b60b78d0a0b54b55e86224c46/src/openrct2-ui/windows/Ride.cpp#L4973-L4995

**Comment by janisozaur** [comment]
Introduced in https://github.com/OpenRCT2/OpenRCT2/pull/26030

**Comment by janisozaur** [comment]
@gibmat can you share more info on the compiler and its settings? We run a fairly large suite in CI, yet it wasn't able to catch this in time. Version and full compilation invocation?

The jury is still out on what to do about this. Can you apply individual patches for your package?

**Comment by gibmat** [comment]
This occurred while building the package on a Debian sid system with gcc. I've included the full command used during the build below. The package build does enable various hardening flags (details at https://manpages.debian.org/unstable/dpkg-dev/dpkg-buildflags.1.en.html#hardening)

It will be trivial to cherry-pick any fix.

```
/usr/bin/c++ --version
c++ (Debian 15.2.0-14) 15.2.0
Copyright (C) 2025 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
/usr/bin/c++ -DDISABLE_VERSION_CHECKER -DDOCDIR=\"/usr/share/doc/openrct2\" -DENABLE_SCRIPTING -DOPENGL_NO_LINK -D_FILE_OFFSET_BITS=64 -D__ENABLE_DISCORD__ -D__WARN_SUGGEST_FINAL_METHODS__ -D__WARN_SUGGEST_FINAL_TYPES__ -I/build/openrct2-0.4.32+ds/DISCORDRPC_PROCESS_INCLUDES -I/build/openrct2-0.4.32+ds -I/build/openrct2-0.4.32+ds/libopenrct2 -I/build/openrct2-0.4.32+ds/src/openrct2-ui/.. -isystem /build/openrct2-0.4.32+ds/src/openrct2/../thirdparty -isystem /usr/include/SDL2 -isystem /build/openrct2-0.4.32+ds/src/openrct2-ui/../thirdparty -isystem /usr/include/libpng16 -isystem /usr/include/freetype2 -g -O2 -ffile-prefix-map=/build/openrct2-0.4.32+ds=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2 -fstrict-overflow -fstrict-aliasing -Werror -Wundef -Wmissing-declarations -Winit-self -Wall -Wextra -Wshadow -Wno-unknown-pragmas -Wno-missing-braces -Wno-comment -Wnonnull -Wno-unused-parameter -Wno-attributes -DDEBUG=0 -fno-char8_t -Wno-deprecated-declarations -std=gnu++20 -fPIE -Wsuggest-override -Wduplicated-cond -Wnon-virtual-dtor -Wduplicated-branches -Wrestrict -Wmissing-field-initializers -Wlogical-op -Wold-style-cast -Wunused-const-variable=1 -Wno-clobbered -Wredundant-decls -Wnull-dereference -Wsuggest-final-types -Wsuggest-final-methods -Wignored-qualifiers -Wstrict-overflow=1 -D_REENTRANT -MD -MT CMakeFiles/openrct2.dir/src/openrct2-ui/windows/Ride.cpp.o -MF CMakeFiles/openrct2.dir/src/openrct2-ui/windows/Ride.cpp.o.d -o CMakeFiles/openrct2.dir/src/openrct2-ui/windows/Ride.cpp.o -c /build/openrct2-0.4.32+ds/src/openrct2-ui/windows/Ride.cpp
```

**Comment by janisozaur** [comment]
Submitted https://gcc.gnu.org/bugzilla/show_bug.cgi?id=124334

Test case distilled to: https://godbolt.org/z/Gqnr5dK35

```
unsigned kImageIndexUndefined;
using a = enum b { c };
struct WindowBase
{
    int d{};
};
class StationObject
{
public:
    unsigned entranceBackIndex;
};
struct IWindowManager
{
    WindowBase* h(WindowBase*, b, a);
    template<typename i, typename... TArgs>
    i* h(b cls, a j, TArgs... args)
    {
        return static_cast<i*>(h(new i(args...), cls, j));
    }
};
struct Ride
{
    StationObject* getStationObject();
};
void n(int&);
WindowBase* RideMainOpen();
a o;
class RideWindow : public WindowBase
{
public:
    RideWindow(Ride)
    {
        ColourOnDrawSecondaryPreview();
    }
    Ride q;
    void ColourOnDrawSecondaryPreview()
    {
        auto r = d;
        n(r);
        auto stationObj = q.getStationObject();
        if (stationObj == nullptr && stationObj->entranceBackIndex == kImageIndexUndefined)
            return;
    }
};
IWindowManager s;
Ride t_c;
static RideWindow* t()
{
    return s.h<RideWindow>(c, o, t_c);
}
WindowBase* RideMainOpen()
{
    t();
    return 0;
}
```
