### PR TITLE
Close #21536: Replace ATOMIC_VAR_INIT() macro with constructor

### LINKED ISSUE #21536: /wrkdirs/usr/ports/games/openrct2/work/OpenRCT2-0.4.9/src/openrct2/network/Socket.cpp:251:41: error: macro 'ATOMIC_VAR_INIT' has been marked as deprecated [-Werror,-Wdeprecated-pragma]
### Operating System

FreeBSD 14.0-RELEASE, amd64

### OpenRCT2 build

0.4.9

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Area(s) with this issue?

This is a development issue

### Describe the issue

Fails to build on FreeBSD 14.0-RELEASE with LLVM 16.0.6 without adding `-Wno-error=deprecated-pragma`:
```
/wrkdirs/usr/ports/games/openrct2/work/OpenRCT2-0.4.9/src/openrct2/network/Socket.cpp:251:41: error: macro 'ATOMIC_VAR_INIT' has been marked as deprecated [-Werror,-Wdeprecated-pragma]                                                                                                              
    std::atomic<SocketStatus> _status = ATOMIC_VAR_INIT(SocketStatus::Closed);                                                                     
                                        ^                                                                                                          
/usr/include/c++/v1/atomic:2662:43: note: macro marked 'deprecated' here                                                                           
#  pragma clang deprecated(ATOMIC_VAR_INIT)                                                                                                        
                                          ^                                                                                                        
1 error generated.
```

### Steps to reproduce

Build the game on FreeBSD 14.0-RELEASE.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by Gymnasiast**

### CODE REVIEW

File: src/openrct2/core/FileIndex.hpp [hunk 1]
```diff
@@ -206,7 +206,7 @@ template<typename TItem> class FileIndex
 
             size_t stepSize = 100; // Handpicked, seems to work well with 4/8 cores.
 
-            std::atomic<size_t> processed = ATOMIC_VAR_INIT(0);
+            std::atomic<size_t> processed = { 0 };
```
Comment (ZehMatt) [inline src/openrct2/core/FileIndex.hpp:209]: Brace initialization doesn't need the assignment operator.

File: src/openrct2/network/Socket.cpp [hunk 2]
```diff
@@ -248,7 +248,7 @@ class Socket
 class TcpSocket final : public ITcpSocket, protected Socket
 {
 private:
-    std::atomic<SocketStatus> _status = ATOMIC_VAR_INIT(SocketStatus::Closed);
+    std::atomic<SocketStatus> _status = { SocketStatus::Closed };
```
Comment (ZehMatt) [inline src/openrct2/network/Socket.cpp:251]: See above.

**Review by tupaschoal — APPROVED** [review]
