### ISSUE TITLE
OpenRCT2 won't build with gcc 14

### ISSUE THREAD

**Issue by Kieltux** [OpenRCT2/OpenRCT2#23180]
### Operating System

openSUSE Tumbleweed

### OpenRCT2 build

Release v0.4.16 - "Brave Sir Robin the Not-Quite-So-Brave-As-Sir-Lancelot"

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

When gcc14 is installed and used to compile OpenRCT2, the code will not build.
It will throw "Werror=stringop-overflow" error:
```
[  192s] In member function ‘ReadWrite’,
[  192s]     inlined from ‘ReadWritePeep’ at /home/abuild/rpmbuild/BUILD/OpenRCT2-0.4.16/src/openrct2/park/ParkFile.cpp:1903:33:
[  192s] /home/abuild/rpmbuild/BUILD/OpenRCT2-0.4.16/src/openrct2/park/../core/OrcaStream.hpp:297:23: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
[  192s]   297 |                     v = ReadInteger<T>();
[  192s]       |                       ^
[  192s] /home/abuild/rpmbuild/BUILD/OpenRCT2-0.4.16/src/openrct2/actions/../core/../entity/Peep.h: In function ‘ReadWritePeep’:
[  192s] /home/abuild/rpmbuild/BUILD/OpenRCT2-0.4.16/src/openrct2/actions/../core/../entity/Peep.h:312:8: note: at offset 288 into destination object ‘<anonymous>’ of size 44
[  192s]   312 | struct Peep : EntityBase
[  192s]       |        ^
[  192s] lto1: all warnings being treated as errors
```
Full Log: https://build.opensuse.org/package/live_build_log/home:Kieltux:branches:games/openrct2/openSUSE_Tumbleweed/x86_64

### Steps to reproduce

Use gcc14 (here gcc14-14.2.1+git10750-1.1) and try to build OpenRCT2.
Builds fine with gcc12-12.3.0+git1204-150000.1.18.1.

**Comment by janisozaur** [comment]
I have only noticed this issue now, sorry. A shame it didn't get addressed in time for 0.4.17.

I haven't looked into it yet, but wouldn't be surprised if that was a GCC issue, we've had problems with that in the past.

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/issues/23122#issuecomment-2526344067 suggests this might be an LTO issue

**Comment by Kieltux** [comment]
Thank you for taking your time. Your hint (build with/without LTO) is the solution my problem.
Added
`%define _lto_cflags %{nil}`
to the .spec file and now OpenRCT2 can be compiled with gcc14.
Thank you.

**Comment by janisozaur** [comment]
We would still like to address this one way or another, so reopening it. Disabling LTO is a workaround.
