### ISSUE TITLE
Can't compile with LTO enabled.

### ISSUE THREAD

**Issue by kiroma** [OpenRCT2/OpenRCT2#6200]
**OS:** Ubuntu 17.04
**Version:** 0.1.2
**Commit:** 82be1de6d0c4c954f9d3463a6de6241cf1899525

If you try to compile OpenRTC with GCC and Linker time optimization on, you will be met with following:
```
[376/376] Linking CXX executable openrct2
FAILED: openrct2 
[Long command truncated for brievity]
/home/kiroma/OpenRCT2/src/openrct2/ride/ride.c: In function ‘ride_create_vehicles’:
/home/kiroma/OpenRCT2/src/openrct2/ride/ride.c:4732:59: error: potential null pointer dereference [-Werror=null-dereference]
     firstTrain.head->prev_vehicle_on_ride = lastTrain.tail->sprite_index;
                                                           ^
/home/kiroma/OpenRCT2/src/openrct2/ride/ride.c:4733:42: error: potential null pointer dereference [-Werror=null-dereference]
     lastTrain.tail->next_vehicle_on_ride = firstTrain.head->sprite_index;
                                          ^
lto1: all warnings being treated as errors
lto-wrapper: fatal error: /usr/bin/c++ returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
```
- [ ] Reproducible in RCT2 (vanilla)?
- [ ] Multiplayer?

**Steps to reproduce:**
1. Add the following flags to CMake command: `-DCMAKE_LINKER=/usr/bin/gcc -DCMAKE_AR=/usr/bin/gcc-ar -DCMAKE_RANLIB=/usr/bin/gcc-ranlib -DCMAKE_CXX_FLAGS=-flto -DCMAKE_C_FLAGS=-flto`
2. Attempt to compile.

**Comment by kiroma** [comment]
Any way I can help?

**Comment by janisozaur** [comment]
It works fine using 40b026a4f on my Arch with GCC 7.2.0 and `-DCMAKE_BUILD_TYPE=Release` in addition to your porvided options. It's slightly weird it does, though, as we had to use pragma to disable `suggest-final` warning in one or two places and they generally don't work in LTO builds (and I do remember explicitly hitting that, but maybe on some older system).

**Comment by kiroma** [comment]
LTO in GCC7 is severely broken, I have already reported 2 separate bug reports on bug tracker, so I wouldn't trust it too much.

**Comment by janisozaur** [comment]
Which version are you using? In that case you're on your own. I doubt Travis could handle the memory requirements of LTO build.

**Comment by kiroma** [comment]
I'm using GCC6.4 on Ubuntu 17.10.
It should also fail on GCC5 but there's a different issue that makes it fail mid-way...

**Comment by janisozaur** [comment]
I have GCC5 lying around on my system, I tried compiling with it. Other than having to disable aforementioned `suggest-final` warnings, it works just fine.

**Comment by kiroma** [comment]
What version of GCC5 do you have?

**Comment by janisozaur** [comment]
```
gcc-5 (GCC) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by kiroma** [comment]
I may have just discovered another bug, this time in GCC5.
```
../src/openrct2/config/IniReader.cpp:153:26: error: ‘stoi’ is not a member of ‘std’
                 result = std::stoi(value);
                          ^
```
I'm on a streak.

**Comment by kiroma** [comment]
Turns out it's a glibc bug.
Anyways, so GCC5 works with -flto? That needs deeper investigation then.

**Comment by janisozaur** [comment]
We have updated the required compiler to GCC 7 and with GCC 8 out the door soon, can you recheck, please?

**Comment by Gymnasiast** [comment]
No answer from OP for > 3 years, and likely to be irrelevant now, so closing this.

**Comment by Thaodan** [comment]
The issue is still there, I think most of the warnings are already present in #17371.
[openrct2-git-r23412.b0ffa9d28e-1-x86_64-build.log](https://github.com/OpenRCT2/OpenRCT2/files/8886816/openrct2-git-r23412.b0ffa9d28e-1-x86_64-build.log)

Here's my build log with all the warnings when building with GCC 12 while LTO is enabled. 

When I added this option `-Wno-error=stringop-overflow` including the ones that I already mentioned in #17371 I could build fine with LTO.
