### ISSUE TITLE
Build error in Launchpad

### ISSUE THREAD

**Issue by Gymnasiast** [OpenRCT2/OpenRCT2#24509]
### Operating System

Ubuntu 24.04

### OpenRCT2 build

5fe3f7b97f167b1ad389cdaa5ff5680cc6073f40

### Base game

RollerCoaster Tycoon 2

### Describe the issue

```
/usr/include/c++/13/bits/new_allocator.h:172: error: ‘operator delete’ called on unallocated object ‘<anonymous>’ [-Werror=free-nonheap-object]
  172 |         _GLIBCXX_OPERATOR_DELETE(_GLIBCXX_SIZED_DEALLOC(__p, __n));
      | 
/usr/src/openrct2-0.4.22-develop-0~2311-202505260018-g5fe3f7b97f~ubuntu24.04.1/src/openrct2-ui/windows/EditorScenarioOptions.cpp: In function ‘__merge_sort_with_buffer’:
/usr/src/openrct2-0.4.22-develop-0~2311-202505260018-g5fe3f7b97f~ubuntu24.04.1/src/openrct2-ui/windows/EditorScenarioOptions.cpp:2219:71: note: declared here
```

May have been caused by https://github.com/OpenRCT2/OpenRCT2/pull/24475 .

### Steps to reproduce

See above

**Comment by janisozaur** [comment]
I saw that, GCC tripping over its own feet. Paste the whole stack trace

**Comment by ZehMatt** [comment]
I don't know why this also uses stable_sort, ordinary sort will do nicely and doesn't require heap allocations.

**Comment by Gymnasiast** [comment]
@ZehMatt Can you create a PR to change that? Hopefully that will also fix the build error. (The code was added by @Harry-Hopkinson , I don’t think he had a particular reason to go far stable_sort.)

**Comment by janisozaur** [comment]
I have updated the launchpad mirror and scheduled a build: https://code.launchpad.net/~openrct2/+archive/ubuntu/nightly/+build/30953122

**Comment by janisozaur** [comment]
Still fails. What's problematic is that it falls at linking with LTO, not at initial compilation.

**Comment by Gymnasiast** [comment]
@janisozaur Can we address this for v0.4.26, or do we demilestone this?

**Comment by janisozaur** [comment]
Moved it to the next milestone

**Comment by janisozaur** [comment]
Just 5 more months now

**Comment by qwertychouskie** [comment]
Still an issue.  For now I disabled 24.04 builds so it won't send me error emails for every new build, but it'd be nice to have it fixed, since most users are probably still on 24.04.

Probably the simplest way to fix would be to disable `-Werror=free-nonheap-object` (or just `Werror` in general) for package builds?

**Comment by qwertychouskie** [comment]
Opened https://github.com/OpenRCT2/OpenRCT2/pull/27150 that Should™ fix the issue for the PPA builds.
