### ISSUE TITLE
Compile fails on ppc64el due to `constexpr long double`

### ISSUE THREAD

**Issue by gibmat** [OpenRCT2/OpenRCT2#17069]
### Operating System

Debian sid, ppc64el

### OpenRCT2 build

OpenRCT2, v0.4.0

### Describe the issue

After updating the Debian packages for OpenRCT2 to v0.4.0, the build for ppc64el failed due to what is apparently a weird gcc bug on that architecture related to how a `long double` is represented:

```
In file included from /<<PKGBUILDDIR>>/src/openrct2/ride/ShopItem.h:12,
                 from /<<PKGBUILDDIR>>/src/openrct2/ride/ShopItem.cpp:10:
/<<PKGBUILDDIR>>/src/openrct2/ride/ShopItem.cpp:29:41:   in ‘constexpr’ expansion of ‘operator""_GBP(2.99999999999999999999999999999998e-1l)’
/<<PKGBUILDDIR>>/src/openrct2/ride/../common.h:98:18: error: ‘(2.99999999999999999999999999999998e-1l * 1.0e+1l)’ is not a constant expression
   98 |     return money * 10;
      |            ~~~~~~^~~~
```

There are some other reports of similar issues online:
https://github.com/mamedev/mame/issues/3157
https://bugzilla.mozilla.org/show_bug.cgi?id=1416170
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=26374

I'm not sure what the correct fix for this would be; maybe removing the `constexpr` from `constexpr money32 operator"" _GBP(long double money) noexcept` as defined in src/openrct2/common.h? Or if a normal `double` would be sufficient, just use that?

There are also several variations on a warning about a narrowing conversion:

```
/<<PKGBUILDDIR>>/src/openrct2/ride/ShopItem.cpp:29:41: error: narrowing conversion of ‘operator""_GBP(2.99999999999999999999999999999998e-1l)’ from ‘money32’ {aka ‘int’} to ‘money16’ {aka ‘short int’} [-Werror=narrowing]
   29 |     /* ShopItem::Balloon */          {  0.30_GBP, 1.40_GBP,   1.40_GBP,  1.40_GBP,   0.90_GBP,      SPR_SHOP_ITEM_BALLOON,             { STR_SHOP_ITEM_PRICE_LABEL_BALLOON,                STR_SHOP_ITEM_SINGULAR_BALLOON,             STR_SHOP_ITEM_PLURAL_BALLOON,               STR_SHOP_ITEM_INDEFINITE_BALLOON,               STR_SHOP_ITEM_DISPLAY_BALLOON             }, SHOP_ITEM_FLAG_IS_SOUVENIR,                           Litter::Type::Rubbish,          0,                ShopItem::None,             PeepThoughtType::BalloonMuch,           PeepThoughtType::Balloon            },
      |                                         ^~~~~~~~
```

Previously, OpenRCT2 0.3.5.1 compiled just fine; full build log is at https://buildd.debian.org/status/fetch.php?pkg=openrct2&arch=ppc64el&ver=0.4.0%2Bds-1&stamp=1650977105&raw=0

### Area(s) with issue?

Building the game

### Steps to reproduce

1. Compile the latest release on a ppc64el box.

**Comment by gibmat** [comment]
I've been able to fix the ppc64el compile errors, but there are a couple changes (patch below) that I'm not 100% sure won't break anything else accidentally -- specifically the changes to `struct ShopItemDescriptor`.

The ppc64el build complains about narrowing conversions when the various `ShopItems` are created. I don't know why only ppc64el complains about this.... It was simple enough to change the `money16` and `money8` fields in that struct to be `money32`. That appears to work, and as long as we're not trying to do a `memcpy()` or something to the struct I think that should be OK. But I'd appreciate confirmation on that.

Secondly, the signature for the user-defined literal `_GBP` method must be a `long double`, but I doubt anyone will actually try to have more "money" than can be represented by a plain `double`, so I've added a cast down to a `double`, which then is happy on ppc64el being used in a `constexpr`. (Also matches the definition of `constexpr money32 ToMoney32FromGBP(double money)` a few lines later that deals with floating-point money conversion.)

I've performed a build locally (amd64) with these two changes, and the game seems to run fine, so I cautiously think these changes should be OK.

```
diff --git a/src/openrct2/common.h b/src/openrct2/common.h
index d22eb49..2495dc7 100644
--- a/src/openrct2/common.h
+++ b/src/openrct2/common.h
@@ -93,9 +93,16 @@ using money64 = fixed64_1dp;
 #define FIXED_2DP(whole, fraction) FIXED_XDP(10, whole, fraction)
 
 // User defined literal to convert money literal to money32
+// For a user defined floating point literal, the parameter type must be a `long double`
+// which is problematic on ppc64el, as the architecture uses a pair of `doubles` to
+// represent that type. This cannot be converted to a `constexpr`. As a work around,
+// statically cast the `long double` down to a `double`. All of the uses of _GBP
+// constants fit just fine, and if anyone really tries to use a gigantic constant that
+// can't fit in a double, they are probably going to be breaking other things anyways.
+// For more details, see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=26374
 constexpr money32 operator"" _GBP(long double money) noexcept
 {
-    return money * 10;
+    return static_cast<double>(money) * 10;
 }
 
 constexpr money32 ToMoney32FromGBP(int32_t money) noexcept
diff --git a/src/openrct2/ride/ShopItem.h b/src/openrct2/ride/ShopItem.h
index e1b42a9..b5f527e 100644
--- a/src/openrct2/ride/ShopItem.h
+++ b/src/openrct2/ride/ShopItem.h
@@ -88,11 +88,11 @@ struct ShopItemStrings
 
 struct ShopItemDescriptor
 {
-    money16 Cost;
-    money16 BaseValue;
-    money16 HotValue;
-    money16 ColdValue;
-    money8 DefaultPrice;
+    money32 Cost;
+    money32 BaseValue;
+    money32 HotValue;
+    money32 ColdValue;
+    money32 DefaultPrice;
     uint32_t Image;
     ShopItemStrings Naming;
     uint16_t Flags;
```

**Comment by qwertychouskie** [comment]
This might have been fixed by the merging of https://github.com/OpenRCT2/OpenRCT2/pull/19469.  Normally I'd use the `ppc64el` PPA builds to check, but PPA builds are currently broken for other reasons (see https://github.com/OpenRCT2/OpenRCT2/issues/19466).  Once PPA builds are working again, I'll revisit whether this issue can be closed.

**Comment by qwertychouskie** [comment]
Compilation is still broken.  Now there only appears to be one error left:

```
In file included from /<<PKGBUILDDIR>>/src/openrct2/ride/ShopItem.h:12,
                 from /<<PKGBUILDDIR>>/src/openrct2/ride/ShopItem.cpp:10:
/<<PKGBUILDDIR>>/src/openrct2/ride/ShopItem.cpp:29:41:   in ‘constexpr’ expansion of ‘operator""_GBP(2.99999999999999999999999999999998e-1l)’
/<<PKGBUILDDIR>>/src/openrct2/ride/../common.h:92:18: error: ‘(2.99999999999999999999999999999998e-1l * 1.0e+1l)’ is not a constant expression
   92 |     return money * 10;
      |            ~~~~~~^~~~
make[3]: *** [CMakeFiles/libopenrct2.dir/build.make:4265: CMakeFiles/libopenrct2.dir/src/openrct2/ride/ShopItem.cpp.o] Error 1
```
(https://launchpadlibrarian.net/654385319/buildlog_ubuntu-jammy-ppc64el.openrct2_0.4.3-develop-0~4200-202303032113-g463234e59~ubuntu22.04.1_BUILDING.txt.gz)

Hopefully this is a simple fix.

**Comment by gibmat** [comment]
Yes, I just confirmed this as well on one of the Debian porter boxes. All the warnings/errors about narrowing conversions are resolved, but the patch to `src/openrct2/common.h` in my second comment above is still needed. (The Debian package does indeed contain that patch, so it's able to build successfully.)

**Comment by qwertychouskie** [comment]
If this change has already been shipping for some time with no known issues, can you submit a PR with the change?
