### ISSUE TITLE
Very often no Android builds are compiled after a PR gets merged

### ISSUE THREAD

**Issue by mrtnptrs** [OpenRCT2/OpenRCT2#6780]
I saw that very often (at least 9 out of 10 times) no Android builds are automatically compiled after a Pull Request gets merged/someone commits something to the developer branch. See: https://openrct2.org/downloads

I suspect this is intentionally done to speed up the building progress and because of not many people using the Android version yet? But it has become pretty stable and hopefully touch screen support will be improved in the future. Now MP will be activated for Android builds, even more people will probably be interested. But by making the Android builds better available, you could interest even more people to make the Android builds even better.

Would it be possible for you to enable the Android builds compiling progress for every merged commit?

Btw @marijnvdwerf You did an amazing job by getting this running on Android :)

_For in the future: it might would be a nice idea to publish OpenRCT2 on Google Play. There you could let people download the stable versions as a standard, but that they can sign up there to get the beta/develop versions every time. This would probably largely increase the involvement of other people in the Android builds and attract more developers for it. I know that publishing on Google Play involves a pretty large fee, but I'm sure that I and many others would like to give you a donation to make this possible :) (and to hopefully tank the sales of RCTC from AtariShit :P) Maybe this would be possible in the future._

**Comment by Gymnasiast** [comment]
This is deliberate, yes.

**Comment by mrtnptrs** [comment]
Ok, but why exactly and what do you think about what I said?

**Comment by janisozaur** [comment]
See https://github.com/OpenRCT2/OpenRCT2/issues/5657

**Comment by mrtnptrs** [comment]
Thanks @janisozaur , so by a cron-job those Android builds should be compiled once in 24 hours.

**Comment by janisozaur** [comment]
Yes, unless I actually want to try something and restart them.

**Comment by mrtnptrs** [comment]
Huh, ok, assuming OpenRCT2.com shows all Android builds, I can see that they are not created every hour:
The last one (from commit f52544d) was created 3 days ago: https://openrct2.org/downloads/develop/f52544d I checked three times and no Android build has been created since then. So it's surely not 24 hours, strange. @janisozaur ?

**Comment by janisozaur** [comment]
Yeah, since they are cron-based, they also need manual inspection in case of failures, like in current case:

```
/usr/local/android-sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: CMakeFiles/openrct2.dir/home/travis/build/OpenRCT2/OpenRCT2/src/openrct2/platform/Platform.Linux.cpp.o: multiple definition of 'Platform::GetFolderPath(SPECIAL_FOLDER)'
/usr/local/android-sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: CMakeFiles/openrct2.dir/home/travis/build/OpenRCT2/OpenRCT2/src/openrct2/platform/Platform.Android.cpp.o: previous definition here
```
Ping @IntelOrca

**Comment by janisozaur** [comment]
In this case it's a regression from https://github.com/OpenRCT2/OpenRCT2/pull/6748, which is missing android compilation guard

**Comment by IntelOrca** [comment]
Is there a docker image for building OpenRCT2 for Android?

**Comment by janisozaur** [comment]
No, it's not needed. You should be able to build it even on Windows, I think, Android Studio comes packaged with all the required bootstrapping and then gradle project resolves dependencies through cmake.

Try this:
```
cd src/openrct2-android
./gradlew app:assemblePR
```
I think it might even work without Android Studio; there's `gradlew.bat` that is aimed at Windows users.

You will have to manually set the path to your SDK and probably also `ANDROID_HOME` environment variable.

**Comment by mrtnptrs** [comment]
So, if I understand it right, there is currently a bug preventing Android builds from being compiled and this problem is a regression from #6748 ?

I will try to build the Android build myself using Android Studio and see how quickly I will fail doing that :P

**Comment by janisozaur** [comment]
The fix should be simple: just make sure the `linux.cpp` file introduced in #6748 is not compiled for Android. There's `ifdef` compile guard in it that needs to be changed.

**Comment by mrtnptrs** [comment]
Sadly I don't know exactly where I should place that 'ifdef' :( Hopefully it gets fixed soon by one of you :)

**Comment by janisozaur** [comment]
https://github.com/OpenRCT2/OpenRCT2/blob/0b45098e0555cfd3e2e60d5eede93120c51d3e9c/src/openrct2/platform/Platform.Linux.cpp#L17

**Comment by mrtnptrs** [comment]
Ok, I will try that. And if that works, can I make a PR about it or would you rather like to do that?

**Comment by janisozaur** [comment]
If you manage to reproduce the bug, fix it and verify it is fixed, I'll take a PR for that

**Comment by mrtnptrs** [comment]
At your service!

**Comment by mrtnptrs** [comment]
Ok, I tried building it multiple times with Android Studio: First it gives and error about using a too old version of Gradle (3.3) and that I have to update it to get it to build and I pressed on "update". After I do that and try to build finally, I get this error: "Error:All flavors must now belong to a named flavor dimension. Learn more at https://d.android.com/r/tools/flavorDimensions-missing-error-message.html"

Did I do something wrong or something? @marijnvdwerf  @janisozaur

**Comment by janisozaur** [comment]
Yeah, I ran into that when I used android studio and I fixed it locally, but then figured it would probably upset the slightly older tools we have set up on CI, so I reset it all and just use gradle.

The bug is not the main matter of this issue, just fix it or let me know I should do it.

**Comment by mrtnptrs** [comment]
Thanks for the fix! I will probably start a new issue for that soon.
