### ISSUE TITLE
/wrkdirs/usr/ports/games/openrct2/work/OpenRCT2-0.4.9/src/openrct2/network/Socket.cpp:251:41: error: macro 'ATOMIC_VAR_INIT' has been marked as deprecated [-Werror,-Wdeprecated-pragma]

### ISSUE THREAD

**Issue by pkubaj** [OpenRCT2/OpenRCT2#21536]
### Operating System

FreeBSD 14.0-RELEASE, amd64

### OpenRCT2 build

0.4.9

### Base game

RollerCoaster Tycoon 2, RollerCoaster Tycoon Classic

### Area(s) with this issue?

This is a development issue

### Describe the issue

Fails to build on FreeBSD 14.0-RELEASE with LLVM 16.0.6 without adding `-Wno-error=deprecated-pragma`:
```
/wrkdirs/usr/ports/games/openrct2/work/OpenRCT2-0.4.9/src/openrct2/network/Socket.cpp:251:41: error: macro 'ATOMIC_VAR_INIT' has been marked as deprecated [-Werror,-Wdeprecated-pragma]                                                                                                              
    std::atomic<SocketStatus> _status = ATOMIC_VAR_INIT(SocketStatus::Closed);                                                                     
                                        ^                                                                                                          
/usr/include/c++/v1/atomic:2662:43: note: macro marked 'deprecated' here                                                                           
#  pragma clang deprecated(ATOMIC_VAR_INIT)                                                                                                        
                                          ^                                                                                                        
1 error generated.
```

### Steps to reproduce

Build the game on FreeBSD 14.0-RELEASE.

**Comment by Gymnasiast** [comment]
From C++ reference:

“This macro is primarily provided for compatibility with C; it behaves the same as the constructor of [std::atomic](https://en.cppreference.com/w/cpp/atomic/atomic).”
