### PR TITLE
Fix line that causes build to fail on Mac

### PR DESCRIPTION
**Pull request by X123M3-256**
When trying to build the game on Mac, I got the following error:

```
/Users/ec2618/Programming/RCT2/OpenRCT2/src/openrct2/platform/Platform.macOS.mm:111:24: error: implicit conversion of NULL constant to 'uintptr_t' (aka 'unsigned long') [-Werror,-Wnull-conversion]
                return NULL;
                ~~~~~~ ^~~~
                       0
1 error generated.
```
I asked about it on the Gitter and was told to submit a PR.

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Regression from #10264.

**Comment by tupaschoal** [comment]
Why didn't it fail on the CI? (I mean, the mac job failed, but it seems it was after it had already compiled)

**Comment by AaronVanGeffen** [comment]
This is speculation, but I think fewer warnings are enabled in the Xcode project compared to the CMake project.
