### PR TITLE
osx: fix locale issues

### LINKED ISSUE #2488: error: use of undeclared identifier 'LC_MEASUREMENT'
#2338 broke the build on OS X :(

It seems like it's even noted in the merged source code:

```c++
//FIXME: LC_MEASUREMENT is GNU specific.
const char *langstring = setlocale(LC_MEASUREMENT, "");
```

### PR DESCRIPTION
**Pull request by LinusU**
This fixes #2488 caused by #2338

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Could you provide a comment in the code explaining LC_MEASUREMENT is GNU-specific on both occurrences?

**Comment by LinusU** [comment]
@Gymnasiast done :+1:

**Comment by IntelOrca** [comment]
As mentioned in gitter, there might be a more native version of doing this for OSX, but this will do for now.
