### PR TITLE
Fix #17069: Fix build on ppc64el architectures

### LINKED ISSUE #17069: Compile fails on ppc64el due to `constexpr long double`
### Operating System

Debian sid, ppc64el

### OpenRCT2 build

OpenRCT2, v0.4.0

### Describe the issue

After updating the Debian packages for OpenRCT2 to v0.4.0, the build for ppc64el failed due to what is apparently a weird gcc bug on that architecture related to how a `long double` is represented:

```
In file included from /<<PKGBUILDDIR>>/src/openrct2/ride/ShopItem.h:12,
                 from /<<PKGBUILDDIR>>/src/openrct2/ride/ShopItem.cpp:10:
/<<PKGBUILDDIR>>/src/openrct2/ride/ShopItem.cpp:29:41:   in ‘constexpr’ expansion of ‘operator""_GBP(2.99999999999999999999999999999998e-1l)’
/<<PKGBUILDDIR>>/src/openrct2/ride/../common.h:98:18: error: ‘(2.99999999999999999999999999999998e-1l * 1.0e+1l)’ is not a constant expression
   98 |     return money * 10;
      |            ~~~~~~^~~~
```

There are some other reports of similar issues online:
https://github.com/mamedev/mame/issues/3157
https://bugzilla.mozilla.org/show_bug.cgi?id=1416170
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=26374

I'm not sure what the correct fix for this would be; maybe removing the `constexpr` from `constexpr money32 operator"" _GBP(long double money) noexcept` as defined in src/openrct2/common.h? Or if a normal `double` would be sufficient, just use that?

There are also several variations on a warning about a narrowing conversion:

```
/<<PKGBUILDDIR>>/src/openrct2/ride/ShopItem.cpp:29:41: error: narrowing conversion of ‘operator""_GBP(2.99999999999999999999999999999998e-1l)’ from ‘money32’ {aka ‘int’} to ‘money16’ {aka ‘short int’} [-Werror=narrowing]
   29 |     /* ShopItem::Balloon */          {  0.30_GBP, 1.40_GBP,   1.40_GBP,  1.40_GBP,   0.90_GBP,      SPR_SHOP_ITEM_BALLOON,             { STR_SHOP_ITEM_PRICE_LABEL_BALLOON,                STR_SHOP_ITEM_SINGULAR_BALLOON,             STR_SHOP_ITEM_PLURAL_BALLOON,               STR_SHOP_ITEM_INDEFINITE_BALLOON,               STR_SHOP_ITEM_DISPLAY_BALLOON             }, SHOP_ITEM_FLAG_IS_SOUVENIR,                           Litter::Type::Rubbish,          0,                ShopItem::None,             PeepThoughtType::BalloonMuch,           PeepThoughtType::Balloon            },
      |                                         ^~~~~~~~
```

Previously, OpenRCT2 0.3.5.1 compiled just fine; full build log is at https://buildd.debian.org/status/fetch.php?pkg=openrct2&arch=ppc64el&ver=0.4.0%2Bds-1&stamp=1650977105&raw=0

### Area(s) with issue?

Building the game

### Steps to reproduce

1. Compile the latest release on a ppc64el box.

### Attachments

_No response_

### PR DESCRIPTION
**Pull request by gibmat**
For a user defined floating point literal, the parameter type must be a `long double` which is problematic on ppc64el, as the architecture uses a pair of `doubles` to represent that type. This cannot be converted to a `constexpr`. As a workaround, statically cast the `long double` down to a `double`. All of the uses of _GBP constants fit just fine, and if anyone really tries to use a gigantic constant that can't fit in a double, they are probably going to be breaking other things anyways. For more details, see https://gcc.gnu.org/bugzilla/show_bug.cgi?id=26374

The Debian packaging of openrct2 has included this patch since 0.4.0, with no reported issues.

### CODE REVIEW

**Review by tupaschoal — COMMENTED** [review]
Wouldn't it be better to change the parameter to actually be just `double`?

**Comment by gibmat** [comment]
Unfortunately there is no parameter list for user-defined literals that's just a `double`: https://en.cppreference.com/w/cpp/language/user_literal#Literal_operators

GCC correctly emits an error if you try to use just a `double`:
```
In file included from /build/openrct2-0.4.3+ds/src/openrct2/core/Console.hpp:12,
                 from /build/openrct2-0.4.3+ds/src/openrct2/Diagnostic.cpp:12:
/build/openrct2-0.4.3+ds/src/openrct2/core/../common.h:96:19: error: 'constexpr money32 operator""_GBP(double)' has invalid argument list
   96 | constexpr money32 operator"" _GBP(double money) noexcept
      |                   ^~~~~~~~
```

**Review by tupaschoal — APPROVED** [review]
I didn't see that coming, how weird :O
