### ISSUE TITLE
build with LTO from version 0.4.16 not possible on fedora

### ISSUE THREAD

**Issue by h3o66** [OpenRCT2/OpenRCT2#23122]
### Operating System

Fedora 40

### OpenRCT2 build

0.4.16

### Base game

RollerCoaster Tycoon 2

### Area(s) with this issue?

This is a development issue

### Describe the issue

The new release does not seem to compile at all with the compiler option `-Werror=stringop-overflow=` on fedora.
That option is default in fedora overall.

error from the compiler / linker:
```
In member function â€˜ReadWriteâ€™,
    inlined from â€˜ReadWritePeepâ€™ at /builddir/build/BUILD/OpenRCT2-0.4.16/src/openrct2/park/ParkFile.cpp:1903:33:
/builddir/build/BUILD/OpenRCT2-0.4.16/src/openrct2/park/../core/OrcaStream.hpp:297:23: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
  297 |                     v = ReadInteger<T>();
      |                       ^
/builddir/build/BUILD/OpenRCT2-0.4.16/src/openrct2/actions/../core/../entity/Peep.h: In function â€˜ReadWritePeepâ€™:
/builddir/build/BUILD/OpenRCT2-0.4.16/src/openrct2/actions/../core/../entity/Peep.h:312:8: note: at offset 288 into destination object â€˜<anonymous>â€™ of size 44
  312 | struct Peep : EntityBase
      |        ^
lto1: all warnings being treated as errors
```

compiler versions:
F39: `GNU 13.3.1`
F40/41/rawhide: `GNU 14.2.1`

failed build on fedora copr:
https://copr.fedorainfracloud.org/coprs/birkch/openrct2/build/8206054/

### Steps to reproduce

1. compile on fedora with compiler options
2. get noted error

**Comment by h3o66** [comment]
ok - still happens with `0.4.17` , the culprint in general seems to be LTO for the linker , error:

```
In member function â€˜ReadWriteâ€™,
    inlined from â€˜ReadWritePeepâ€™ at /builddir/build/BUILD/openrct2-0.4.17-build/OpenRCT2-0.4.17/src/openrct2/park/ParkFile.cpp:1904:33:
/builddir/build/BUILD/openrct2-0.4.17-build/OpenRCT2-0.4.17/src/openrct2/park/../core/OrcaStream.hpp:297:23: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
  297 |                     v = ReadInteger<T>();
      |                       ^
/builddir/build/BUILD/openrct2-0.4.17-build/OpenRCT2-0.4.17/src/openrct2/actions/../core/../entity/Peep.h: In function â€˜ReadWritePeepâ€™:
/builddir/build/BUILD/openrct2-0.4.17-build/OpenRCT2-0.4.17/src/openrct2/actions/../core/../entity/Peep.h:313:8: note: at offset 288 into destination object â€˜<anonymous>â€™ of size 44
  313 | struct Peep : EntityBase
      |        ^
lto1: all warnings being treated as errors
```

failed build with LTO:
https://copr.fedorainfracloud.org/coprs/birkch/openrct2/build/8364047/

successful without LTO:
https://copr.fedorainfracloud.org/coprs/birkch/openrct2/build/8364106/

**Comment by janisozaur** [comment]
duplicate of https://github.com/OpenRCT2/OpenRCT2/issues/23180

**Comment by h3o66** [comment]
> duplicate of [#23180](https://github.com/OpenRCT2/OpenRCT2/issues/23180). Also I like how they pasted `‘` and `’` correctly

Well, the output is apparently broken in the fedora copr, so the encoding was like this already presented to me.
