### PR TITLE
Change ordering of includes

### PR DESCRIPTION
**Pull request by pkubaj**
It fixes build with LLVM 6.0.1 and GCC 7.3.0 on FreeBSD 11.2-RELEASE.

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
It appears to violate are `clang-format` styles, meaning CI doesn't pass… The section should probably be exempt from applying clang-format, then.

Could you add `// clang format off` before and `// clang format on` after the section in question?

**Comment by janisozaur** [comment]
Why is this necessary? Is this a bug with FreeBSD's headers?

**Comment by pkubaj** [comment]
I'm not sure why this is necessary, TBH.
But without this I'm getting:
```
(00:02:29) In file included from /wrkdirs/usr/ports/games/openrct2/work/OpenRCT2-0.2.1/src/openrct2/platform/Platform.Linux.cpp:16:
(00:02:29) /usr/include/sys/sysctl.h:1036:25: error: C++ requires a type specifier for all declarations
(00:02:29) int     sysctl(const int *, u_int, void *, size_t *, const void *, size_t);
(00:02:29)                             ^
(00:02:29) 1 error generated.
```
Coincidentally, `u_int` is typedef'd in `sys/types.h`. I thought that maybe compiler parses source line-by-line, so if it doesn't know some type beforehand, it throws error. It looks like it's true.

File: src/openrct2/platform/Platform.Linux.cpp [hunk 1]
```diff
@@ -13,8 +13,10 @@
 #    include <pwd.h>
 #    if defined(__FreeBSD__)
 #        include <stddef.h>
+// clang format off
```
Comment (Broxzier) [inline src/openrct2/platform/Platform.Linux.cpp]: I'd like to see a comment that explains why this is necessary here, so others who stumble upon it understand.

File: src/openrct2/platform/Platform.Linux.cpp [hunk 2]
```diff
@@ -13,8 +13,11 @@
 #    include <pwd.h>
 #    if defined(__FreeBSD__)
 #        include <stddef.h>
-#        include <sys/sysctl.h>
+// clang format off
```
Comment (janisozaur) [inline src/openrct2/platform/Platform.Linux.cpp]: it's `clang-format`, not `clang format`

Comment (AaronVanGeffen) [reply src/openrct2/platform/Platform.Linux.cpp]: That's on me, I suggested the latter. Sorry.

File: src/openrct2/platform/Platform.Linux.cpp [hunk 3]
```diff
@@ -13,8 +13,11 @@
 #    include <pwd.h>
 #    if defined(__FreeBSD__)
 #        include <stddef.h>
-#        include <sys/sysctl.h>
+// clang-format off
+// formatting check is disabled so that u_int, typedef'd in sys/types.h may be included before including sys/sysctl.h
 #        include <sys/types.h>
```
Comment (jbeich) [inline src/openrct2/platform/Platform.Linux.cpp]: `// clang-format off` can be avoided if you replace `<sys/types.h>` with `<sys/param.h>`. The latter already includes `<sys/types.h>` and is frequently used together with `<sys/sysctl.h>` due to `__FreeBSD_version` and `nitems()` e.g., try replacing `4` with `nitems(mib)` in
https://github.com/OpenRCT2/OpenRCT2/blob/2bffda8aff309ef0642190983b2fd2384553abb2/src/openrct2/platform/Platform.Linux.cpp#L155

`KERN_PROC_PATHNAME` is also supported on DragonFly and NetBSD. The latter actually [requires](http://netbsd.gw.com/cgi-bin/man-cgi?sysctl+3+NetBSD-current) `<sys/param.h>` rather than `<sys/types.h>`.

**Comment by pkubaj** [comment]
Thanks! I updated this PR to use sys/param.h instead.

**Comment by janisozaur** [comment]
LGTM. I will squash this though.

File: src/openrct2/platform/Platform.Linux.cpp (hunk 3 above)
Comment (janisozaur) [reply src/openrct2/platform/Platform.Linux.cpp]: @jbeich do you consider it done now? If not please leave a comment or submit a PR

**Comment by janisozaur** [comment]
I'd like to wait for sign-off from @jbeich

**Comment by jbeich** [comment]
Looks OK.

**Comment by AaronVanGeffen** [comment]
@janisozaur It seems the clang-format comments got lost in the merge?

**Comment by Broxzier** [comment]
@AaronVanGeffen It's not needed anymore, pkubaj changed the include: https://github.com/OpenRCT2/OpenRCT2/pull/7941#issuecomment-417411471
