### PR TITLE
Extended compiler warnings

### PR DESCRIPTION
**Pull request by janisozaur**
This should cover large chunk of https://github.com/OpenRCT2/OpenRCT2/issues/4401

CMake builds will no use `-Werror -Wundef -Wmissing-declarations -Winit-self -Wall -Wno-unknown-pragmas -Wno-unused-function -Wno-missing-braces -Wno-comment`

There's one last error in clang builds which I'm not sure how to solve (the simplest way of removing it may not be the best one):
```
/home/travis/build/janisozaur/OpenRCT2/src/ride/track_design.c:624:10: error: 
      explicitly assigning value of variable of type 'uint8'
      (aka 'unsigned char') to itself [-Werror,-Wself-assign]
                                                bh = bh;
                                                ~~ ^ ~~
```
see https://github.com/OpenRCT2/OpenRCT2/blob/develop/src/ride/track_design.c#L624

### CODE REVIEW

**Comment by Gymnasiast** [comment]
Why would you want to assign a variable to itself? Isn't it just a typo or something made redundant by a refactor?

**Comment by janisozaur** [comment]
This was introduced in 49e02fda, relevant place in vanilla (as commented) seems to be `0x6d0b51`, can someone check?

**Comment by duncanspumpkin** [comment]
Its because it makes it much easier to write the if branch if there is something in it.

**Comment by duncanspumpkin** [comment]
And yeah it is meant to be like that but feel free to refactor it out.

**Comment by IntelOrca** [comment]
The if, else if just needs extracting out into a new function which returns true or false.

**Comment by janisozaur** [comment]
Updated, clang is now green.
