### ISSUE TITLE
Fails to build with OpenSSL 3.0

### ISSUE THREAD

**Issue by gibmat** [OpenRCT2/OpenRCT2#16726]
### Operating System

Debian experimental

### OpenRCT2 build

Current develop branch (fea9254)

### Describe the issue

Debian has OpenSSL 3.0 staged in experimental, and it was found that OpenRCT2 fails to build:

```
[snip]

-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found suitable version "3.0.1", minimum required is "1.0.0")

[snip]

[ 23%] Building CXX object CMakeFiles/libopenrct2.dir/src/openrct2/core/File.cpp.o
/home/gibmat/build/OpenRCT2-develop/src/openrct2/core/Crypt.OpenSSL.cpp: In member function ‘void OpenSSLRsaKey::SetKey(std::string_view, bool)’:
/home/gibmat/build/OpenRCT2-develop/src/openrct2/core/Crypt.OpenSSL.cpp:191:58: error: ‘RSA* PEM_read_bio_RSAPrivateKey(BIO*, RSA**, int (*)(char*, int, int, void*), void*)’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  191 |         auto rsa = isPrivate ? PEM_read_bio_RSAPrivateKey(bio, nullptr, nullptr, nullptr)
      |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/gibmat/build/OpenRCT2-develop/src/openrct2/core/Crypt.OpenSSL.cpp:15:
/usr/include/openssl/pem.h:447:1: note: declared here
  447 | DECLARE_PEM_rw_cb_attr(OSSL_DEPRECATEDIN_3_0, RSAPrivateKey, RSA)
      | ^~~~~~~~~~~~~~~~~~~~~~
/home/gibmat/build/OpenRCT2-develop/src/openrct2/core/Crypt.OpenSSL.cpp:192:57: error: ‘RSA* PEM_read_bio_RSAPublicKey(BIO*, RSA**, int (*)(char*, int, int, void*), void*)’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  192 |                              : PEM_read_bio_RSAPublicKey(bio, nullptr, nullptr, nullptr);
      |                                ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/gibmat/build/OpenRCT2-develop/src/openrct2/core/Crypt.OpenSSL.cpp:15:
/usr/include/openssl/pem.h:448:1: note: declared here
  448 | DECLARE_PEM_rw_attr(OSSL_DEPRECATEDIN_3_0, RSAPublicKey, RSA)
      | ^~~~~~~~~~~~~~~~~~~
/home/gibmat/build/OpenRCT2-develop/src/openrct2/core/Crypt.OpenSSL.cpp:201:40: error: ‘int RSA_check_key(const RSA*)’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  201 |         if (isPrivate && !RSA_check_key(rsa))
      |                           ~~~~~~~~~~~~~^~~~~
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/pem.h:23,
                 from /home/gibmat/build/OpenRCT2-develop/src/openrct2/core/Crypt.OpenSSL.cpp:15:
/usr/include/openssl/rsa.h:278:27: note: declared here
  278 | OSSL_DEPRECATEDIN_3_0 int RSA_check_key(const RSA *);
      |                           ^~~~~~~~~~~~~
/home/gibmat/build/OpenRCT2-develop/src/openrct2/core/Crypt.OpenSSL.cpp:203:21: error: ‘void RSA_free(RSA*)’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  203 |             RSA_free(rsa);
      |             ~~~~~~~~^~~~~
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/pem.h:23,
                 from /home/gibmat/build/OpenRCT2-develop/src/openrct2/core/Crypt.OpenSSL.cpp:15:
/usr/include/openssl/rsa.h:293:28: note: declared here
  293 | OSSL_DEPRECATEDIN_3_0 void RSA_free(RSA *r);
      |                            ^~~~~~~~
/home/gibmat/build/OpenRCT2-develop/src/openrct2/core/Crypt.OpenSSL.cpp:210:26: error: ‘int EVP_PKEY_set1_RSA(EVP_PKEY*, rsa_st*)’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  210 |         EVP_PKEY_set1_RSA(_evpKey, rsa);
      |         ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
In file included from /home/gibmat/build/OpenRCT2-develop/src/openrct2/core/Crypt.OpenSSL.cpp:14:
/usr/include/openssl/evp.h:1344:5: note: declared here
 1344 | int EVP_PKEY_set1_RSA(EVP_PKEY *pkey, struct rsa_st *key);
      |     ^~~~~~~~~~~~~~~~~
/home/gibmat/build/OpenRCT2-develop/src/openrct2/core/Crypt.OpenSSL.cpp:211:17: error: ‘void RSA_free(RSA*)’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  211 |         RSA_free(rsa);
      |         ~~~~~~~~^~~~~
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/pem.h:23,
                 from /home/gibmat/build/OpenRCT2-develop/src/openrct2/core/Crypt.OpenSSL.cpp:15:
/usr/include/openssl/rsa.h:293:28: note: declared here
  293 | OSSL_DEPRECATEDIN_3_0 void RSA_free(RSA *r);
      |                            ^~~~~~~~
/home/gibmat/build/OpenRCT2-develop/src/openrct2/core/Crypt.OpenSSL.cpp: In member function ‘std::string OpenSSLRsaKey::GetKey(bool)’:
/home/gibmat/build/OpenRCT2-develop/src/openrct2/core/Crypt.OpenSSL.cpp:221:37: error: ‘rsa_st* EVP_PKEY_get1_RSA(EVP_PKEY*)’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  221 |         auto rsa = EVP_PKEY_get1_RSA(_evpKey);
      |                    ~~~~~~~~~~~~~~~~~^~~~~~~~~
In file included from /home/gibmat/build/OpenRCT2-develop/src/openrct2/core/Crypt.OpenSSL.cpp:14:
/usr/include/openssl/evp.h:1348:16: note: declared here
 1348 | struct rsa_st *EVP_PKEY_get1_RSA(EVP_PKEY *pkey);
      |                ^~~~~~~~~~~~~~~~~
[ 23%] Building CXX object CMakeFiles/libopenrct2.dir/src/openrct2/core/FileScanner.cpp.o
/home/gibmat/build/OpenRCT2-develop/src/openrct2/core/Crypt.OpenSSL.cpp:233:62: error: ‘int PEM_write_bio_RSAPrivateKey(BIO*, const RSA*, const EVP_CIPHER*, const unsigned char*, int, int (*)(char*, int, int, void*), void*)’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  233 |         auto status = isPrivate ? PEM_write_bio_RSAPrivateKey(bio, rsa, nullptr, nullptr, 0, nullptr, nullptr)
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/gibmat/build/OpenRCT2-develop/src/openrct2/core/Crypt.OpenSSL.cpp:15:
/usr/include/openssl/pem.h:447:1: note: declared here
  447 | DECLARE_PEM_rw_cb_attr(OSSL_DEPRECATEDIN_3_0, RSAPrivateKey, RSA)
      | ^~~~~~~~~~~~~~~~~~~~~~
/home/gibmat/build/OpenRCT2-develop/src/openrct2/core/Crypt.OpenSSL.cpp:234:61: error: ‘int PEM_write_bio_RSAPublicKey(BIO*, const RSA*)’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  234 |                                 : PEM_write_bio_RSAPublicKey(bio, rsa);
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
In file included from /home/gibmat/build/OpenRCT2-develop/src/openrct2/core/Crypt.OpenSSL.cpp:15:
/usr/include/openssl/pem.h:448:1: note: declared here
  448 | DECLARE_PEM_rw_attr(OSSL_DEPRECATEDIN_3_0, RSAPublicKey, RSA)
      | ^~~~~~~~~~~~~~~~~~~
/home/gibmat/build/OpenRCT2-develop/src/openrct2/core/Crypt.OpenSSL.cpp:238:21: error: ‘void RSA_free(RSA*)’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  238 |             RSA_free(rsa);
      |             ~~~~~~~~^~~~~
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/pem.h:23,
                 from /home/gibmat/build/OpenRCT2-develop/src/openrct2/core/Crypt.OpenSSL.cpp:15:
/usr/include/openssl/rsa.h:293:28: note: declared here
  293 | OSSL_DEPRECATEDIN_3_0 void RSA_free(RSA *r);
      |                            ^~~~~~~~
/home/gibmat/build/OpenRCT2-develop/src/openrct2/core/Crypt.OpenSSL.cpp:241:17: error: ‘void RSA_free(RSA*)’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  241 |         RSA_free(rsa);
      |         ~~~~~~~~^~~~~
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/pem.h:23,
                 from /home/gibmat/build/OpenRCT2-develop/src/openrct2/core/Crypt.OpenSSL.cpp:15:
/usr/include/openssl/rsa.h:293:28: note: declared here
  293 | OSSL_DEPRECATEDIN_3_0 void RSA_free(RSA *r);
      |                            ^~~~~~~~
```

The OpenSSL project has a migration guide that may be useful: https://www.openssl.org/docs/man3.0/man7/migration_guide.html

### Area(s) with issue?

Building the game

### Steps to reproduce

1. Build the current develop branch on a system with OpenSSL 3.0 installed.

**Comment by RelevantWorm** [comment]
This is reproducible on Ubuntu 22.04 with OpenSSL 3.0.2
Is there a workaround?

```
[ 22%] Building CXX object CMakeFiles/libopenrct2.dir/src/openrct2/core/Crypt.OpenSSL.cpp.o
/usr/local/src/OpenRCT2/src/openrct2/core/Crypt.OpenSSL.cpp: In member function ‘void OpenSSLRsaKey::SetKey(std::string_view, bool)’:
/usr/local/src/OpenRCT2/src/openrct2/core/Crypt.OpenSSL.cpp:191:58: error: ‘RSA* PEM_read_bio_RSAPrivateKey(BIO*, RSA**, int (*)(char*, int, int, void*), void*)’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  191 |         auto rsa = isPrivate ? PEM_read_bio_RSAPrivateKey(bio, nullptr, nullptr, nullptr)
      |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/src/OpenRCT2/src/openrct2/core/Crypt.OpenSSL.cpp:15:
/usr/include/openssl/pem.h:447:1: note: declared here
  447 | DECLARE_PEM_rw_cb_attr(OSSL_DEPRECATEDIN_3_0, RSAPrivateKey, RSA)
      | ^~~~~~~~~~~~~~~~~~~~~~
/usr/local/src/OpenRCT2/src/openrct2/core/Crypt.OpenSSL.cpp:192:57: error: ‘RSA* PEM_read_bio_RSAPublicKey(BIO*, RSA**, int (*)(char*, int, int, void*), void*)’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  192 |                              : PEM_read_bio_RSAPublicKey(bio, nullptr, nullptr, nullptr);
      |                                ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/src/OpenRCT2/src/openrct2/core/Crypt.OpenSSL.cpp:15:
/usr/include/openssl/pem.h:448:1: note: declared here
  448 | DECLARE_PEM_rw_attr(OSSL_DEPRECATEDIN_3_0, RSAPublicKey, RSA)
      | ^~~~~~~~~~~~~~~~~~~
/usr/local/src/OpenRCT2/src/openrct2/core/Crypt.OpenSSL.cpp:201:40: error: ‘int RSA_check_key(const RSA*)’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  201 |         if (isPrivate && !RSA_check_key(rsa))
      |                           ~~~~~~~~~~~~~^~~~~
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/pem.h:23,
                 from /usr/local/src/OpenRCT2/src/openrct2/core/Crypt.OpenSSL.cpp:15:
/usr/include/openssl/rsa.h:278:27: note: declared here
  278 | OSSL_DEPRECATEDIN_3_0 int RSA_check_key(const RSA *);
      |                           ^~~~~~~~~~~~~
/usr/local/src/OpenRCT2/src/openrct2/core/Crypt.OpenSSL.cpp:203:21: error: ‘void RSA_free(RSA*)’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  203 |             RSA_free(rsa);
      |             ~~~~~~~~^~~~~
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/pem.h:23,
                 from /usr/local/src/OpenRCT2/src/openrct2/core/Crypt.OpenSSL.cpp:15:
/usr/include/openssl/rsa.h:293:28: note: declared here
  293 | OSSL_DEPRECATEDIN_3_0 void RSA_free(RSA *r);
      |                            ^~~~~~~~
/usr/local/src/OpenRCT2/src/openrct2/core/Crypt.OpenSSL.cpp:210:26: error: ‘int EVP_PKEY_set1_RSA(EVP_PKEY*, rsa_st*)’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  210 |         EVP_PKEY_set1_RSA(_evpKey, rsa);
      |         ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
In file included from /usr/local/src/OpenRCT2/src/openrct2/core/Crypt.OpenSSL.cpp:14:
/usr/include/openssl/evp.h:1344:5: note: declared here
 1344 | int EVP_PKEY_set1_RSA(EVP_PKEY *pkey, struct rsa_st *key);
      |     ^~~~~~~~~~~~~~~~~
/usr/local/src/OpenRCT2/src/openrct2/core/Crypt.OpenSSL.cpp:211:17: error: ‘void RSA_free(RSA*)’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  211 |         RSA_free(rsa);
      |         ~~~~~~~~^~~~~
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/pem.h:23,
                 from /usr/local/src/OpenRCT2/src/openrct2/core/Crypt.OpenSSL.cpp:15:
/usr/include/openssl/rsa.h:293:28: note: declared here
  293 | OSSL_DEPRECATEDIN_3_0 void RSA_free(RSA *r);
      |                            ^~~~~~~~
/usr/local/src/OpenRCT2/src/openrct2/core/Crypt.OpenSSL.cpp: In member function ‘std::string OpenSSLRsaKey::GetKey(bool)’:
/usr/local/src/OpenRCT2/src/openrct2/core/Crypt.OpenSSL.cpp:221:37: error: ‘rsa_st* EVP_PKEY_get1_RSA(EVP_PKEY*)’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  221 |         auto rsa = EVP_PKEY_get1_RSA(_evpKey);
      |                    ~~~~~~~~~~~~~~~~~^~~~~~~~~
In file included from /usr/local/src/OpenRCT2/src/openrct2/core/Crypt.OpenSSL.cpp:14:
/usr/include/openssl/evp.h:1348:16: note: declared here
 1348 | struct rsa_st *EVP_PKEY_get1_RSA(EVP_PKEY *pkey);
      |                ^~~~~~~~~~~~~~~~~
/usr/local/src/OpenRCT2/src/openrct2/core/Crypt.OpenSSL.cpp:233:62: error: ‘int PEM_write_bio_RSAPrivateKey(BIO*, const RSA*, const EVP_CIPHER*, const unsigned char*, int, int (*)(char*, int, int, void*), void*)’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  233 |         auto status = isPrivate ? PEM_write_bio_RSAPrivateKey(bio, rsa, nullptr, nullptr, 0, nullptr, nullptr)
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/src/OpenRCT2/src/openrct2/core/Crypt.OpenSSL.cpp:15:
/usr/include/openssl/pem.h:447:1: note: declared here
  447 | DECLARE_PEM_rw_cb_attr(OSSL_DEPRECATEDIN_3_0, RSAPrivateKey, RSA)
      | ^~~~~~~~~~~~~~~~~~~~~~
/usr/local/src/OpenRCT2/src/openrct2/core/Crypt.OpenSSL.cpp:234:61: error: ‘int PEM_write_bio_RSAPublicKey(BIO*, const RSA*)’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  234 |                                 : PEM_write_bio_RSAPublicKey(bio, rsa);
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
In file included from /usr/local/src/OpenRCT2/src/openrct2/core/Crypt.OpenSSL.cpp:15:
/usr/include/openssl/pem.h:448:1: note: declared here
  448 | DECLARE_PEM_rw_attr(OSSL_DEPRECATEDIN_3_0, RSAPublicKey, RSA)
      | ^~~~~~~~~~~~~~~~~~~
/usr/local/src/OpenRCT2/src/openrct2/core/Crypt.OpenSSL.cpp:238:21: error: ‘void RSA_free(RSA*)’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  238 |             RSA_free(rsa);
      |             ~~~~~~~~^~~~~
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/pem.h:23,
                 from /usr/local/src/OpenRCT2/src/openrct2/core/Crypt.OpenSSL.cpp:15:
/usr/include/openssl/rsa.h:293:28: note: declared here
  293 | OSSL_DEPRECATEDIN_3_0 void RSA_free(RSA *r);
      |                            ^~~~~~~~
/usr/local/src/OpenRCT2/src/openrct2/core/Crypt.OpenSSL.cpp:241:17: error: ‘void RSA_free(RSA*)’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  241 |         RSA_free(rsa);
      |         ~~~~~~~~^~~~~
In file included from /usr/include/openssl/x509.h:36,
                 from /usr/include/openssl/pem.h:23,
                 from /usr/local/src/OpenRCT2/src/openrct2/core/Crypt.OpenSSL.cpp:15:
/usr/include/openssl/rsa.h:293:28: note: declared here
  293 | OSSL_DEPRECATEDIN_3_0 void RSA_free(RSA *r);
      |                            ^~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/libopenrct2.dir/build.make:1826: CMakeFiles/libopenrct2.dir/src/openrct2/core/Crypt.OpenSSL.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:89: CMakeFiles/libopenrct2.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

****  Installation failed. Aborting package creation.

```

**Comment by janisozaur** [comment]
Disable deprecated declarations warning. We will start working on properly addressing that soon.

**Comment by h3o66** [comment]
fyi: Fedora 36+ has the same issue with the default build flags:
https://copr.fedorainfracloud.org/coprs/birkch/openrct2/build/4282683/

**Comment by loqs** [comment]
> Do you have the cmake flag that would disable those warnings? I've tried -CMAKE_WARN_DEPRECATED=FALSE and -Wno-deprecated but I'm still getting deprecated errors while building.
Appending either of ' -Wno-error=deprecated-declarations'  or ' -DOPENSSL_API_COMPAT=0x1010000L to CXXFLAGS worked for me.
